# Generated by Django 6.0 on 2026-02-25 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_tour_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='category',
            field=models.CharField(choices=[('safari', 'Safari'), ('weekend', 'Weekend Getaway')], default='safari', max_length=20),
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('budget_type', models.CharField(choices=[('budget', 'Budget'), ('mid', 'Mid-range'), ('luxury', 'Luxury')], max_length=20)),
                ('description', models.TextField()),
                ('features', models.TextField()),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='tours.tour')),
            ],
        ),
    ]
