# Generated by Django 6.0 on 2026-01-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_unique_tour_booking_per_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reference',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
    ]
